backend:
  name: github
  repo: bamazon/bamazon.github.io
  branch: master
  site_domain: adoring-murdock-e75973.netlify.com
media_folder: "/image/uploads" # Media files will be stored in the repo under static/images/uploads
collections:
  - name: "semesters" # Used in routes, e.g., /admin/collections/blog
    identifier_field: semester-num
    label: "Semesters" # Used in the UI
    folder: "/_semesters" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "sem{{semester-num}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "semester-default"

      - label: "Semester"
        name: "semester-num"
        widget: "number"

      - label: "Icon"
        name: "fa-class"
        widget: "string"

      - label: "PageTitle"
        name: "pagetitle"
        widget: "string"

      - label: "Links"
        name: "links"
        widget: "list"
        allow_add: true
        fields:
          - label: "Name"
            name: name
            widget: string
          - label: "URL"
            name: url
            widget: string
          - label: "Fa-class"
            name: fa-class
            widget: string 
          - label: "Other"
            name: other
            widget: list
            fields: 
             - label: "Name"
               name: name
               widget: string
             - label: "URL"
               name: url
               widget: "string"

  - name: "common-data" # Used in routes, e.g., /admin/collections/blog
    label: "Common Data" # Used in the UI
    files:
     - label: "Footer Links"
       name: "footer-links"
       file: _data/footer-links.yml
       fields:
        - label: "Links"
          name: "links"
          widget: "list"
          allow_add: true
          fields:
           - label: "Name"
             name: "name"
             widget: "string"
           - label: "URL"
             name: "url"
             widget: string
     - label: "Old page semester"
       name: "old"
       file: old.html
       fields:
        - label: "Semester"
          name: "semester-num"
          widget: "number"